insert into symptoms (name, category, description, sort_order) values
  ('Hot flashes', 'vasomotor', 'Sudden feelings of warmth, usually in the face, neck, and chest', 1),
  ('Night sweats', 'vasomotor', 'Hot flashes that occur during sleep, often causing awakening', 2),
  ('Chills', 'vasomotor', 'Feeling cold after a hot flash', 3),
  ('Insomnia', 'sleep', 'Difficulty falling or staying asleep', 10),
  ('Early waking', 'sleep', 'Waking earlier than desired and unable to return to sleep', 11),
  ('Restless sleep', 'sleep', 'Frequent awakenings or poor sleep quality', 12),
  ('Anxiety', 'mood', 'Feelings of worry, nervousness, or unease', 20),
  ('Mood swings', 'mood', 'Rapid, unexpected changes in mood', 21),
  ('Irritability', 'mood', 'Feeling easily frustrated or angered', 22),
  ('Depression', 'mood', 'Persistent sadness, hopelessness, or low mood', 23),
  ('Brain fog', 'cognitive', 'Difficulty concentrating, memory lapses, or mental cloudiness', 24),
  ('Memory lapses', 'cognitive', 'Forgetting things more often than usual', 25),
  ('Fatigue', 'physical', 'Persistent tiredness not relieved by rest', 30),
  ('Joint pain', 'physical', 'Aching, stiffness, or discomfort in joints', 31),
  ('Muscle aches', 'physical', 'General muscle soreness or discomfort', 32),
  ('Headaches', 'physical', 'Head pain ranging from mild to severe', 33),
  ('Heart palpitations', 'physical', 'Awareness of your heartbeat, or irregular beats', 34),
  ('Dizziness', 'physical', 'Lightheadedness or feeling off-balance', 35),
  ('Weight gain', 'physical', 'Unexplained weight increase, often around the abdomen', 36),
  ('Bloating', 'physical', 'Feeling of abdominal fullness or swelling', 37),
  ('Vaginal dryness', 'urogenital', 'Decreased moisture and lubrication in the vagina', 40),
  ('Painful intercourse', 'urogenital', 'Discomfort or pain during sexual activity', 41),
  ('Decreased libido', 'urogenital', 'Reduced interest in sexual activity', 42),
  ('Urinary urgency', 'urogenital', 'Sudden, strong need to urinate', 43),
  ('Frequent urination', 'urogenital', 'Needing to urinate more often than usual', 44),
  ('Dry skin', 'skin_hair', 'Skin that feels rough, tight, or flaky', 50),
  ('Hair thinning', 'skin_hair', 'Noticeable decrease in hair density or texture', 51),
  ('Acne', 'skin_hair', 'Breakouts or skin blemishes', 52),
  ('Breast tenderness', 'physical', 'Soreness or sensitivity in the breasts', 53),
  ('Tingling/numbness', 'physical', 'Unusual sensations in hands, feet, or other areas', 54)
on conflict (name) do nothing;
